#cloud-config
package_update: true
packages:
  - nginx
  - curl

systemd:
  units:
    - name: nginx.service
      enabled: true
      command: start

runcmd:
  # Scarica il file h1 dalla repository GitHub pubblica
  - curl -o /var/www/html/index.html https://raw.githubusercontent.com/Enrisox/Enrisox/main/h1

  # Avvia NGINX
  - systemctl start nginx
  - systemctl enable nginx
